#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define BUFFER_SIZE 1024

int main(int argc, char *argv[]) {
	char buffer[BUFFER_SIZE];

	if (argc < 4) {
		fprintf(stderr, "Usage: %s <version> <array_name> <file1> <file2> ... <fileN>\n", argv[0]);
		return 1;
	}

	// Parse and validate GLSL version
	const char *version = argv[1];
	if (strlen(version) < 3 || strlen(version) > 4 || strspn(version, "0123456789") != strlen(version)) {
		fprintf(stderr, "Error: Invalid GLSL version '%s'. Must be numeric (e.g., 120, 150).\n", version);
		return 1;
	}

	// Open the output file
	snprintf(buffer, sizeof(buffer), "%s.h", argv[2]);
	FILE *output_file = fopen(buffer, "w");
	if (output_file == NULL) {
		perror("Error opening output file");
		return 1;
	}

	// Write header file metadata
	fprintf(output_file, "/*\n");
	fprintf(output_file, " * GLSL Shader Code Embedded as C Header\n");
	fprintf(output_file, " * Generated by: %s\n", argv[0]);
	fprintf(output_file, " * GLSL Version: %s\n", version);
	fprintf(output_file, " */\n\n");

	// Write the array declaration and GLSL version directive
	fprintf(output_file, "const char *%s_start =\n", argv[2]);
	fprintf(output_file, "\t\"#version %s\\n\"", version);

	// Process each input file
	for (int i = 3; i < argc; i++) {
		FILE *input_file = fopen(argv[i], "r");
		if (input_file == NULL) {
			perror("Error opening input file");
			fclose(output_file);
			return 1;
		}

		int is_empty = 1;
		while (fgets(buffer, sizeof(buffer), input_file) != NULL) {
			if (!strchr(buffer, '\n') && !feof(input_file)) {
				fprintf(stderr, "Error: Line too long in file '%s'.\n", argv[i]);
				fclose(input_file);
				fclose(output_file);
				return 1;
			}
			size_t len = strlen(buffer);
			if (len > 0 && buffer[len - 1] == '\n') {
				buffer[len - 1] = '\0'; // Remove newline
			}
			fprintf(output_file, "\n\t\"%s\\n\"", buffer);
			is_empty = 0;
		}

		if (is_empty) {
			fprintf(stderr, "Warning: File '%s' is empty.\n", argv[i]);
		}

		fclose(input_file);
	}

	// Finalize the array declaration
	fprintf(output_file, ";\n\n");
	fclose(output_file);

	return 0;
}
